// Channel
export const CREATE_CHANNEL_REQUEST = 'CREATE_CHANNEL_REQUEST';
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';
export const CREATE_CHANNEL_FAILURE = 'CREATE_CHANNEL_FAILURE';

export const FETCH_CHANNEL_QUEUE_REQUEST = 'FETCH_CHANNEL_QUEUE_REQUEST';
export const FETCH_CHANNEL_QUEUE_SUCCESS = 'FETCH_CHANNEL_QUEUE_SUCCESS';
export const FETCH_CHANNEL_QUEUE_FAILURE = 'FETCH_CHANNEL_QUEUE_FAILURE';

export const ADD_TO_CHANNEL_QUEUE_REQUEST = 'ADD_TO_CHANNEL_QUEUE_REQUEST';
export const ADD_TO_CHANNEL_QUEUE_SUCCESS = 'ADD_TO_CHANNEL_QUEUE_SUCCESS';
export const ADD_TO_CHANNEL_QUEUE_FAILURE = 'ADD_TO_CHANNEL_QUEUE_FAILURE';

export const SKIP_QUEUE_ITEM_REQUEST = 'SKIP_QUEUE_ITEM_REQUEST';
export const SKIP_QUEUE_ITEM_SUCCESS = 'SKIP_QUEUE_ITEM_SUCCESS';
export const SKIP_QUEUE_ITEM_FAILURE = 'SKIP_QUEUE_ITEM_FAILURE';

