// Persistance
export const HYDRATION_COMPLETED = 'HYDRATION_COMPLETED';

// Channel
export const CREATE_CHANNEL_REQUEST = 'CREATE_CHANNEL_REQUEST';
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';
export const CREATE_CHANNEL_FAILURE = 'CREATE_CHANNEL_FAILURE';

export const FETCH_CHANNEL_REQUEST = 'FETCH_CHANNEL_REQUEST';
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS';
export const FETCH_CHANNEL_FAILURE = 'FETCH_CHANNEL_FAILURE';

export const ADD_USER_TO_CHANNEL_REQUEST = 'ADD_USER_TO_CHANNEL_REQUEST';
export const ADD_USER_TO_CHANNEL_SUCCESS = 'ADD_USER_TO_CHANNEL_SUCCESS';
export const ADD_USER_TO_CHANNEL_FAILURE = 'ADD_USER_TO_CHANNEL_FAILURE';

// Queue
export const FETCH_CHANNEL_QUEUE_REQUEST = 'FETCH_CHANNEL_QUEUE_REQUEST';
export const FETCH_CHANNEL_QUEUE_SUCCESS = 'FETCH_CHANNEL_QUEUE_SUCCESS';
export const FETCH_CHANNEL_QUEUE_FAILURE = 'FETCH_CHANNEL_QUEUE_FAILURE';

export const ADD_TO_CHANNEL_QUEUE_REQUEST = 'ADD_TO_CHANNEL_QUEUE_REQUEST';
export const ADD_TO_CHANNEL_QUEUE_SUCCESS = 'ADD_TO_CHANNEL_QUEUE_SUCCESS';
export const ADD_TO_CHANNEL_QUEUE_FAILURE = 'ADD_TO_CHANNEL_QUEUE_FAILURE';

export const SKIP_QUEUE_ITEM_REQUEST = 'SKIP_QUEUE_ITEM_REQUEST';
export const SKIP_QUEUE_ITEM_SUCCESS = 'SKIP_QUEUE_ITEM_SUCCESS';
export const SKIP_QUEUE_ITEM_FAILURE = 'SKIP_QUEUE_ITEM_FAILURE';

// Search
export const SEARCH_MUSIC_REQUEST = 'SEARCH_MUSIC_REQUEST';
export const SEARCH_MUSIC_SUCCESS = 'SEARCH_MUSIC_SUCCESS';
export const SEARCH_MUSIC_FAILURE = 'SEARCH_MUSIC_FAILURE';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';